# Generated by Django 2.1 on 2021-08-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('staff_code', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_register.Position')),
            ],
        ),
    ]
